"""Alembic environment.

Phase 1: real domain models now exist (app/models/), so
target_metadata points at Base.metadata and `alembic revision
--autogenerate` becomes usable for future migrations. This
migration set (0002_phase1_identity) was still hand-written and
reviewed rather than autogenerated, since the authoring sandbox has
no live Postgres to diff against (Section 1: migrations reviewed
manually for anything non-trivial) — autogenerate is available for
Phase 2 onward where a live DB is expected during development.
"""

import asyncio
import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# apps/api is not on sys.path when Alembic is invoked from the repo
# root (only pytest's `pythonpath` ini option handles that for
# tests) — add it explicitly so `from app.models import Base` works.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "apps" / "api"))

from app.models import Base  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

db_url = os.environ.get("DATABASE_URL")
if db_url:
    config.set_main_option("sqlalchemy.url", db_url)


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
